# Generated by Django 6.0.2 on 2026-02-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmouvement', '0002_stock_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stockmouvement.stock'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('stock_bas', 'Stock Bas'), ('vente_anormale', 'Vente Anormale'), ('audit_purge_warning', "Avertissement purge journal d'audit")], max_length=50),
        ),
    ]
