# Generated by Django 6.0.2 on 2026-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text="Nom d'utilisateur unique (optionnel)", max_length=30, null=True, unique=True),
        ),
    ]
