# Generated by Django 6.0.2 on 2026-06-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'Variante', 'verbose_name_plural': 'Variantes'},
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('NEW', 'Nouveau'), ('BESTSELLER', 'Meilleure vente'), ('HOT', 'Tendance'), ('SET', 'Ensemble'), ('CLASSIC', 'Classique')], max_length=20, null=True, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, verbose_name='Couleurs disponibles (hex)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.TextField(blank=True, default='', verbose_name='Composition / Tissu'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='👕', max_length=10, verbose_name='Icône emoji'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié sur le site web'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_produit',
            field=models.CharField(blank=True, help_text='Auto-généré si laissé vide (ex: PROD-00001)', max_length=100, null=True, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Image principale (fichier)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Image principale (URL externe)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='Attributs'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Coût d'achat (FCFA)"),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente (FCFA)'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taille / Variante'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500, verbose_name='URL Cloudinary')),
                ('cloudinary_public_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Identifiant Cloudinary (public_id)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image de produit',
                'verbose_name_plural': 'Images de produit',
                'db_table': 'product_image',
                'ordering': ['product', 'order'],
            },
        ),
    ]
