# Generated by Django 6.0.2 on 2026-06-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_ajout_champs_site_et_model_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
